config/routes.rb
Rails.application.routes.draw do
  resources :places, constraints: { format: :html }
  devise_for :users
  resources :users, only: [:index, :show]
  devise_scope :user do
    authenticated :user do
      root 'places#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user

  validates :user, :name, :latitude, :longitude, presence: true
  
  has_many :shares
  has_many :shared_users, source: :user, through: :shares
  
  scope :shared_public, -> { where(is_public: true) }
  scope :shared_with, ->(user) { joins(:shares).where(shares: {user_id: user}) }
  scope :not_cteated_by, ->(user) { where.not(user_id: user) }
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  
  validates :name, :email, presence: true
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  has_many :shares
  has_many :shared_places, source: :place, through: :shares
  
  has_many :created_places, class_name: "Place"
  
  scope :all_except, ->(user) { where.not(id: user) }

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = current_user.created_places
    @places += Place.shared_public.not_cteated_by(current_user)
    @places += Place.shared_with(current_user)
    if @places.blank?
      redirect_to new_place_url, notice: "You don't have any shared places yet. Would you like to create one?"
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
    unless current_user == @place.user
      redirect_to @place, notice: 'You are not the creator of this place!'
    end
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        p @place.errors
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if current_user == @place.user
        if @place.update(place_params)
          format.html { redirect_to @place, notice: 'Place was successfully updated.' }
          format.json { render :show, status: :ok, location: @place }
        else
          format.html { render :edit }
          format.json { render json: @place.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    unless current_user == @place.user
      redirect_to places_url, notice: 'You are not the creator of this place!'
    end
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude, :is_public, shared_user_ids: []).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if @user == current_user
      redirect_to places_url
    else
      @shared_places = @user.created_places.shared_with(current_user)
      @shared_places += @user.created_places.where(is_public: true)
      if @shared_places.blank?
        redirect_to users_url, notice: "There's no shared place with you by this user."
      end
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share.Place</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://openlayers.org/en/v5.3.0/css/ol.css" type="text/css">
    <!-- Openlayers CSS file-->
    <%= favicon_link_tag asset_path('marker_logo.png') %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'users/shared/navbar' %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, 
      class: "form-control", 
      label: false, 
      placeholder: 'Name' %>
    <%= f.input :latitude, 
      label: false,
      placeholder: 'Latitude' %>
    <%= f.input :longitude, 
      label: false,
      placeholder: 'Longitude' %>
    <%= f.input :is_public %>
    <%= f.association :shared_users, 
      collection: User.all_except(current_user), 
      label_method: :name, 
      value_method: :id, 
      as: :check_boxes, 
      include_blank: true, 
      include_hidden: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary block full-width m-b" %>
  </div>
<% end %>

app/views/places/edit.html.erb
<div class="middle-box loginscreen animated fadeInDown">
  <h4>Editing Place</h4>
  
  <%= render 'form', place: @place %>
  
  <%= link_to 'Show', @place %> |
  <%= link_to 'Back', places_path %>
</div>

app/views/places/index.html.erb
<div class="card-header bg-info text-white d-flex">
  <h3 class="text-white">Places</h3>
  <%= link_to new_place_path, class: "text-white align-middle ml-auto btn btn-danger" do %>
    <i class="fas fa-plus"></i> New Place
  <% end %>
</div>
<div class="container">
  <div class="row">
    
    <div class="col-6">
      <div id="map"></div>
    </div>
    <div class="col-6">
      <table class="table table-striped text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Public?</th>
            <th>Shared By</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @places.each do |place| %>
            <tr>
              <td><%= place.name %></td>
              <td><%= place.latitude %></td>
              <td><%= place.longitude %></td>
              <td>
                <% if place.is_public.present? %>
                  <i class="fa fa-check" aria-hidden="true"></i>
                <% else %>
                  <i class="fa fa-times" aria-hidden="true"></i>
                <% end %>
              </td>
              <% if place.user == current_user %>
                <td class="text-muted"><i class="fa fa-user" aria-hidden="true"></i> <%= place.user.name %></td>
              <% else %>
                <td>
                  <%= link_to place.user do %>
                    <i class="fa fa-user-secret" aria-hidden="true"></i> <%= place.user.name %>
                  <% end %>
                </td>
              <% end %>
              <td><%= link_to 'Show', place %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script src="https://openlayers.org/en/v5.3.0/build/ol.js" type="text/javascript"></script>
<!-- Openlayesr JS fIle -->
<script type="text/javascript">
  var baseMapLayer = new ol.layer.Tile({
    source: new ol.source.OSM()
  });
  var map = new ol.Map({
    target: 'map',
    layers: [baseMapLayer],
    view: new ol.View({
            center: ol.proj.fromLonLat([<%=@places.first.longitude%>, <%=@places.first.latitude%>]), 
            zoom: 10 //Initial Zoom Level
          })
  });
  
  var featuresArray = []
  <% @places.each do |place| %>
    featuresArray.push(
      new ol.Feature({
        geometry: new ol.geom.Point(
          ol.proj.fromLonLat([<%= place.longitude %>, <%= place.latitude %>])
        )
      })
    );
  <% end %>
  featuresArray.forEach(myFunction);

  function myFunction(value) {
    value.setStyle(new ol.style.Style({
        image: new ol.style.Icon(({
          color: '#ffcd46',
          crossOrigin: 'anonymous',
          src: '<%= asset_path('marker.png') %>'
        }))
    }))
  }
  
  var vectorSource = new ol.source.Vector({
    features: featuresArray
  });
  var markerVectorLayer = new ol.layer.Vector({
    source: vectorSource,
  });
  map.addLayer(markerVectorLayer);
</script>

app/views/places/new.html.erb
<div class="middle-box loginscreen animated fadeInDown">
  <h4 class="text-center">New Place</h4>
  <%= render 'form', place: @place %>
  
  <%= link_to 'Back', places_path, class: "btn btn-sm btn-light btn-block" %>
</div>

app/views/places/show.html.erb
<div class="container">
  <div class="row">
    
    <div class="col-8">
      <div id="map"></div>
    </div>
    <div class="col-4">
      <p>
        <strong>Name:</strong>
        <%= @place.name %>
      </p>

      <p>
        <strong>Latitude:</strong>
        <%= @place.latitude %>
      </p>

      <p>
        <strong>Longitude:</strong>
        <%= @place.longitude %>
      </p>
      
      <p>
        <strong>Is public:</strong>
        <%= @place.is_public %>
      </p>
      
      <p>
        <strong>Shared with:</strong>
        <% @place.shared_users.each do |shared_user| %>
          <li><%= shared_user.name %></li>
        <% end %>
      </p>

      <%= link_to 'Edit', edit_place_path(@place) %> |
      <%= link_to 'Back', places_path %>
    </div>
  </div>
</div>

<script src="https://openlayers.org/en/v5.3.0/build/ol.js" type="text/javascript"></script>
<!-- Openlayesr JS fIle -->
<script type="text/javascript">
  var baseMapLayer = new ol.layer.Tile({
    source: new ol.source.OSM()
  });
  var map = new ol.Map({
    target: 'map',
    layers: [baseMapLayer],
    view: new ol.View({
            center: ol.proj.fromLonLat([<%= @place.longitude %>, <%= @place.latitude %>]), 
            zoom: 10 //Initial Zoom Level
          })
  });
  //Adding a marker on the map
  var marker = new ol.Feature({
    geometry: new ol.geom.Point(
      ol.proj.fromLonLat([<%= @place.longitude %>, <%= @place.latitude %>])
    )
  });
  marker.setStyle(new ol.style.Style({
      image: new ol.style.Icon(({
        color: '#ffcd46',
        crossOrigin: 'anonymous',
        src: '<%= asset_path('marker.png') %>'
      }))
  }));
  
  var vectorSource = new ol.source.Vector({
    features: [marker]
  });
  var markerVectorLayer = new ol.layer.Vector({
    source: vectorSource,
  });
  map.addLayer(markerVectorLayer);
</script>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="card-header bg-info">
  <h3 class="text-white text-center">Users</h3>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Email</th>
      <th>Username</th>
      <th>Registered on</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td class="d-inline-block text-truncate" style="max-width: 250px;"><%= user.slug %></td>
        <td><%= user.created_at.strftime("%F") %></td>
        <td><%= link_to 'Shared Places', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-sm btn-light btn-block" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-sm btn-light btn-block" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to places_path, class: 'navbar-brand' do %>
    <%= image_tag("marker_logo.png", height: 32) %> Share.Place
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Users', users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item ">
        <%= link_to 'Places', places_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <a href="#" class="nav-link disabled">Logged in as <strong><%= current_user.name %></strong></a>
        <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link' %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
        <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/show.html.erb
<div class="card-header bg-info text-white d-flex">
  <h3 class="text-white">Places</h3>
  <%= link_to users_path, class: "text-white align-middle ml-auto btn btn-danger" do %>
    <i class="fas fa-arrow-left"></i> Back
  <% end %>
</div>
<div class="container">
  <div class="row">
    
    <div class="col-6">
      <div id="map"></div>
    </div>
    <div class="col-6">
      <table class="table table-striped text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Is public?</th>
            <th class="text-center">Shared By</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @shared_places.each do |place| %>
            <tr>
              <td><%= place.name %></td>
              <td><%= place.latitude %></td>
              <td><%= place.longitude %></td>
              <td class="text-center">
                <% if place.is_public.present? %>
                  <i class="fa fa-check" aria-hidden="true"></i>
                <% else %>
                  <i class="fa fa-times" aria-hidden="true"></i>
                <% end %>
              </td>
              <% if place.user == current_user %>
                <td><i class="fa fa-user" aria-hidden="true"></i> <%= place.user.name %></td>
              <% else %>
                <td><i class="fa fa-user-secret" aria-hidden="true"></i> <%= place.user.name %></td>
              <% end %>
              <td><%= link_to 'Show', place %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script src="https://openlayers.org/en/v5.3.0/build/ol.js" type="text/javascript"></script>
<!-- Openlayesr JS fIle -->
<%= javascript_pack_tag 'map' %>
<!-- Our map file -->
<script type="text/javascript">
  var baseMapLayer = new ol.layer.Tile({
    source: new ol.source.OSM()
  });
  var map = new ol.Map({
    target: 'map',
    layers: [baseMapLayer],
    view: new ol.View({
            center: ol.proj.fromLonLat([<%=@shared_places.first.longitude%>, <%=@shared_places.first.latitude%>]), 
            zoom: 10 //Initial Zoom Level
          })
  });
  
  var featuresArray = []
  <% @shared_places.each do |place| %>
    featuresArray.push(
      new ol.Feature({
        geometry: new ol.geom.Point(
          ol.proj.fromLonLat([<%=place.longitude%>, <%=place.latitude%>])
        )
      })
    );
  <% end %>
  featuresArray.forEach(myFunction);

  function myFunction(value) {
    value.setStyle(new ol.style.Style({
        image: new ol.style.Icon(({
          color: '#ffcd46',
          crossOrigin: 'anonymous',
          src: '<%= asset_path('marker.png') %>'
        }))
    }))
  }
  
  var vectorSource = new ol.source.Vector({
    features: featuresArray
  });
  var markerVectorLayer = new ol.layer.Vector({
    source: vectorSource,
  });
  map.addLayer(markerVectorLayer);
</script>